framework:
    messenger:
        default_bus: command.bus
        buses:
            query.bus: ~

            command.bus:
                middleware:
                    - validation
                    - 'App\SharedKernel\Messenger\Middleware\DatabaseTransactionMiddleware'
                    - 'App\SharedKernel\Messenger\Middleware\DomainEventDispatcherMiddleware'

            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - 'App\SharedKernel\Messenger\Middleware\DomainEventDispatcherMiddleware'

        transports:
            message_broker_publisher:
                dsn: '%env(AMQP_TRANSPORT_DSN)%'
                serializer: App\SharedKernel\Messenger\JsonMessageSerializer
                options:
                    exchange:
                        name: 'microservices.authentication'
                        type: direct
                    queues: []

        routing:
            App\Domain\Event\UserWasCreated: message_broker_publisher
            App\Domain\Event\EmailConfirmed: message_broker_publisher

when@test:
    framework:
        messenger:
            transports:
                message_broker_publisher: 'in-memory://'