authentication.user.create:
  path: /auth/user
  controller: App\UI\API\CreateUser\CreateUserAction
  methods: [POST]

authentication.user.get:
  path: /auth/user
  controller: App\UI\API\GetUser\GetUserAction
  methods: [GET]

authentication.user.confirm_email:
  path: /auth/user/confirm/{token}
  controller: App\UI\API\ConfirmEmail\ConfirmEmailAction
  methods: [GET]

authentication.user.generate_token:
  path: /auth/user/token
  controller: App\UI\API\GenerateToken\GenerateAccessTokenAction
  methods: [POST]

authentication.user.invalid_token:
  path: /auth/user/token
  controller: App\UI\API\InvalidToken\InvalidTokenAction
  methods: [DELETE]
