parameters:
    amqp.host: '%env(resolve:AMQP_HOST)%'
    amqp.port: '%env(resolve:AMQP_PORT)%'
    amqp.user: '%env(resolve:AMQP_USER)%'
    amqp.password: '%env(resolve:AMQP_PASSWORD)%'
    amqp.vhost: '%env(resolve:AMQP_VHOST)%'

    access_token.secret_key: '%env(resolve:JWT_ACCESS_TOKEN_SECRET_KEY)%'
    access_token.algorithm: '%env(resolve:JWT_ACCESS_TOKEN_ALGORITHM)%'

    refresh_token.secret_key: '%env(resolve:JWT_REFRESH_TOKEN_SECRET_KEY)%'
    refresh_token.algorithm: '%env(resolve:JWT_REFRESH_TOKEN_ALGORITHM)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        App\SharedKernel\Messenger\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\SharedKernel\Messenger\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

        App\SharedKernel\Messenger\EventHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    amqp_factory:
        class: App\SharedKernel\Event\AMQP\RabbitMQFactory
        arguments:
            $configurations: '%amqp_clients%'
            $connection: '@amqp_connection'

    PhpAmqpLib\Connection\AMQPConnectionFactory: ~

    amqp_connection:
        class: PhpAmqpLib\Connection\AbstractConnection
        factory: ['@PhpAmqpLib\Connection\AMQPConnectionFactory', 'create']
        arguments: ['@PhpAmqpLib\Connection\AMQPConnectionConfig']

    App\Infrastructure\Event\Handler\UserWasRegisteredEventHandler:
        arguments:
            $publisher: '@=service("amqp_factory").getPublisher("user_was_registered")'

    PhpAmqpLib\Connection\AMQPConnectionConfig:
        calls:
            - setIsLazy: [true]
            - setIoType: ['socket']
            - setHost: ['%amqp.host%']
            - setPort: ['%amqp.port%']
            - setUser: ['%amqp.user%']
            - setPassword: ['%amqp.password%']
            - setVhost: ['%amqp.vhost%']

    App\Infrastructure\Domain\AccessTokenService:
        arguments:
            $secretKey: '%access_token.secret_key%'
            $algorithm: '%access_token.algorithm%'

    App\Infrastructure\Domain\RefreshTokenService:
        arguments:
            $secretKey: '%refresh_token.secret_key%'
            $algorithm: '%refresh_token.algorithm%'
