parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        App\SharedKernel\Messenger\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\SharedKernel\Messenger\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

        App\SharedKernel\Messenger\EventHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
